# GHC 8.4
resolver: lts-12.25

packages:
- .

extra-deps:
- xmonad-0.15
- xmonad-contrib-0.15

# Override default flag values for local packages and extra-deps
flags: {}
  # # I can't actually run the generated 'generatemanpage' tool:
  # # it depends on having local xmonad sources available.
  # xmonad:
  #   generatemanpage: true
