# GHC 9.0.2
resolver: nightly-2022-02-19

packages:
- .

extra-deps:
- xmonad-0.17.0
- xmonad-contrib-0.17.0

# Override default flag values for local packages and extra-deps
flags: {}
  # # I can't actually run the generated 'generatemanpage' tool:
  # # it depends on having local xmonad sources available.
  # xmonad:
  #   generatemanpage: true
